# Generated by Django 5.1.11 on 2025-08-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0002_etablissementinvitation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, help_text='Établissement auquel appartient cet utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('chef_etablissement', "Chef d'établissement"), ('professeur', 'Professeur'), ('cpe', "CPE (Conseiller Principal d'Éducation)"), ('parent', 'Parent')], help_text="Rôle de l'utilisateur dans l'établissement", max_length=20, verbose_name='Rôle'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'chef_etablissement')), fields=('etablissement',), name='unique_chef_per_etablissement'),
        ),
    ]
