# Generated by Django 5.1.11 on 2025-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_etablissement_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifiant_auto',
            field=models.CharField(blank=True, help_text='Identifiant généré automatiquement (ex: ETB01-PROF-2024-001)', max_length=50, verbose_name='Identifiant automatique'),
        ),
        migrations.AddField(
            model_name='user',
            name='premiere_connexion',
            field=models.BooleanField(default=True, help_text="Indique si l'utilisateur doit changer son mot de passe à la première connexion", verbose_name='Première connexion'),
        ),
    ]
