# Generated by Django 5.1.11 on 2025-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='options_import',
            field=models.JSONField(blank=True, default=dict, help_text="Données de traçabilité d'import (professeur principal en attente, etc.)", verbose_name="Options d'import"),
        ),
    ]
