# Generated by Django 5.1.11 on 2025-08-25 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email de la personne qui gérera cet établissement', max_length=254, verbose_name="Email du chef d'établissement")),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token d'invitation")),
                ('used', models.BooleanField(default=False, verbose_name='Invitation utilisée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisée le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='schools.etablissement', verbose_name='Établissement')),
                ('user_created', models.ForeignKey(blank=True, help_text="Utilisateur qui a accepté l'invitation", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
            ],
            options={
                'verbose_name': "Invitation d'établissement",
                'verbose_name_plural': "Invitations d'établissements",
                'ordering': ['-created_at'],
            },
        ),
    ]
