# Generated by Django 5.1.11 on 2025-08-26 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_etablissementinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_import', models.CharField(choices=[('personnel', 'Import Personnel'), ('classes', 'Import Classes'), ('eleves', 'Import Élèves'), ('cours', 'Import Cours')], max_length=20, verbose_name="Type d'import")),
                ('nom_session', models.CharField(help_text="Ex: 'Rentrée 2024', 'Personnel Septembre'", max_length=100, verbose_name='Nom de session')),
                ('fichier_csv', models.FileField(help_text='Fichier CSV à importer', upload_to='imports/%Y/%m/', verbose_name='Fichier CSV')),
                ('statut', models.CharField(choices=[('uploaded', 'Fichier uploadé'), ('validated', 'Données validées'), ('processing', 'Import en cours'), ('completed', 'Terminé avec succès'), ('error', 'Erreur'), ('cancelled', 'Annulé')], default='uploaded', max_length=20, verbose_name='Statut')),
                ('options_import', models.JSONField(default=dict, help_text="Configuration spécifique à ce type d'import", verbose_name="Options d'import")),
                ('resultats', models.JSONField(default=dict, help_text="Statistiques et erreurs de l'import", verbose_name='Résultats')),
                ('donnees_preview', models.JSONField(default=list, help_text='Échantillon des données à importer', verbose_name='Aperçu des données')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': "Session d'import",
                'verbose_name_plural': "Sessions d'import",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('debug', 'Debug'), ('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=10, verbose_name='Niveau')),
                ('message', models.TextField(help_text="Description détaillée de l'action ou erreur", verbose_name='Message')),
                ('donnees_contexte', models.JSONField(default=dict, help_text='Données contextuelles pour debugging', verbose_name='Contexte')),
                ('ligne_csv', models.PositiveIntegerField(blank=True, help_text='Numéro de ligne dans le CSV concerné', null=True, verbose_name='Ligne CSV')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.importsession', verbose_name="Session d'import")),
            ],
            options={
                'verbose_name': "Log d'import",
                'verbose_name_plural': "Logs d'import",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email de la personne invitée', max_length=254, verbose_name='Email invité')),
                ('role_prevu', models.CharField(choices=[('professeur', 'Professeur'), ('cpe', 'CPE'), ('parent', 'Parent')], max_length=20, verbose_name='Rôle prévu')),
                ('donnees_import', models.JSONField(default=dict, help_text='Données originales du CSV pour cette invitation', verbose_name="Données d'import")),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Invitation envoyée'), ('accepted', 'Invitation acceptée'), ('expired', 'Invitation expirée'), ('error', 'Erreur')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
                ('invitation_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.etablissementinvitation', verbose_name='Invitation personnel')),
                ('user_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_creees', to='imports.importsession', verbose_name="Session d'import")),
            ],
            options={
                'verbose_name': "Invitation d'import",
                'verbose_name_plural': "Invitations d'import",
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('import_session', 'email'), name='unique_invitation_per_session_email')],
            },
        ),
    ]
