# Generated by Django 5.1.11 on 2025-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='progression',
            field=models.JSONField(default=dict, help_text="État détaillé de la progression de l'import", verbose_name='Progression'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='stats_invitations',
            field=models.JSONField(default=dict, help_text='Suivi du statut des invitations créées', verbose_name='Statistiques invitations'),
        ),
    ]
