# Generated by Django 5.1.11 on 2025-08-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importsession_progression_and_more'),
        ('schools', '0002_etablissementinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsession',
            name='stats_invitations',
        ),
        migrations.AlterField(
            model_name='importsession',
            name='type_import',
            field=models.CharField(choices=[('personnel', 'Import Personnel'), ('classes', 'Import Classes'), ('eleves', 'Import Élèves')], max_length=20, verbose_name="Type d'import"),
        ),
        migrations.CreateModel(
            name='ComptesGeneres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_de_passe_temporaire', models.CharField(help_text='Mot de passe généré automatiquement - à usage unique', max_length=50, verbose_name='Mot de passe temporaire')),
                ('fiche_imprimee', models.BooleanField(default=False, help_text="Indique si la fiche d'identifiant a été imprimée", verbose_name='Fiche imprimée')),
                ('distribue', models.BooleanField(default=False, help_text='Indique si les identifiants ont été remis en main propre', verbose_name='Distribué')),
                ('date_distribution', models.DateTimeField(blank=True, help_text='Date de remise des identifiants au bénéficiaire', null=True, verbose_name='Date de distribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('distribuee_par', models.ForeignKey(blank=True, help_text='Personne qui a effectué la distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Distribuée par')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_generes', to='imports.importsession', verbose_name="Session d'import")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
            ],
            options={
                'verbose_name': 'Compte généré',
                'verbose_name_plural': 'Comptes générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ImportInvitation',
        ),
        migrations.AddConstraint(
            model_name='comptesgeneres',
            constraint=models.UniqueConstraint(fields=('import_session', 'user'), name='unique_compte_per_session_user'),
        ),
    ]
