# Generated by Django 5.1.11 on 2025-08-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_remove_importsession_stats_invitations_and_more'),
        ('schools', '0002_etablissementinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='nb_comptes_crees',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImportIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Rôle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('last_id', models.PositiveIntegerField(default=0)),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
            ],
            options={
                'unique_together': {('etablissement', 'role', 'year')},
            },
        ),
    ]
