# Generated by Django 5.1.11 on 2025-08-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importsession_nb_comptes_crees_importidsequence'),
        ('schools', '0002_etablissementinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importidsequence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='importidsequence',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='import_session',
        ),
        migrations.AlterModelOptions(
            name='comptesgeneres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importsession',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='comptesgeneres',
            name='unique_compte_per_session_user',
        ),
        migrations.RemoveField(
            model_name='comptesgeneres',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comptesgeneres',
            name='distribuee_par',
        ),
        migrations.RemoveField(
            model_name='comptesgeneres',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='comptesgeneres',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='donnees_preview',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='options_import',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='date_distribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='distribue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='fiche_imprimee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='import_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.importsession'),
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='mot_de_passe_temporaire',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comptesgeneres',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='fichier_csv',
            field=models.FileField(upload_to='imports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='nom_session',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='resultats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='statut',
            field=models.CharField(choices=[('uploaded', 'Fichier uploadé'), ('validated', 'Données validées'), ('processing', 'Import en cours'), ('completed', 'Terminé'), ('error', 'Erreur')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='type_import',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('classes', 'Classes'), ('eleves', 'Élèves')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ImportIdSequence',
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
