# Generated by Django 5.1.11 on 2025-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_alter_importidsequence_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
