# Generated by Django 5.1.11 on 2025-08-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_importsession_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsession',
            name='temp_field',
        ),
    ]
