# Generated by Django 5.1.11 on 2025-08-26 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('schools', '0002_etablissementinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField(help_text='Début du cours', verbose_name='Date et heure de début')),
                ('date_heure_fin', models.DateTimeField(help_text='Fin du cours', verbose_name='Date et heure de fin')),
                ('salle', models.CharField(blank=True, help_text='Salle de cours (optionnel)', max_length=50, verbose_name='Salle')),
                ('type_cours', models.CharField(choices=[('cours', 'Cours magistral'), ('td', 'Travaux dirigés'), ('tp', 'Travaux pratiques'), ('controle', 'Contrôle/Évaluation'), ('autre', 'Autre')], default='cours', max_length=20, verbose_name='Type de cours')),
                ('annule', models.BooleanField(default=False, help_text='Ce cours a été annulé', verbose_name='Cours annulé')),
                ('motif_annulation', models.TextField(blank=True, help_text="Raison de l'annulation du cours", verbose_name="Motif d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.classe', verbose_name='Classe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'professeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['date_heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('absence', 'Absence'), ('retard', 'Retard'), ('depart_anticipe', 'Départ anticipé')], default='absence', max_length=20, verbose_name="Type d'absence")),
                ('heure_constat', models.TimeField(help_text="Heure à laquelle l'absence/retard a été constaté", verbose_name='Heure de constat')),
                ('justifiee', models.BooleanField(default=False, help_text="L'absence a été justifiée par un responsable", verbose_name='Justifiée')),
                ('motif_justification', models.TextField(blank=True, help_text="Raison donnée pour justifier l'absence", verbose_name='Motif de justification')),
                ('date_justification', models.DateTimeField(blank=True, help_text="Quand l'absence a été justifiée", null=True, verbose_name='Date de justification')),
                ('commentaire_prof', models.TextField(blank=True, help_text='Observations du professeur', verbose_name='Commentaire du professeur')),
                ('notification_envoyee', models.BooleanField(default=False, help_text='Une notification a été envoyée aux parents', verbose_name='Notification envoyée')),
                ('date_notification', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(help_text="Professeur qui a saisi l'absence", on_delete=django.db.models.deletion.CASCADE, related_name='absences_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='academic.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(help_text='Établissement auquel appartient cet enregistrement', on_delete=django.db.models.deletion.CASCADE, to='schools.etablissement', verbose_name='Établissement')),
                ('justifiee_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['cpe', 'chef_etablissement']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_validees', to=settings.AUTH_USER_MODEL, verbose_name='Justifiée par')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='attendance.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-cours__date_heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'cours'), name='unique_absence_per_eleve_cours')],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesAbsences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField(help_text='Date de début de la période de calcul', verbose_name='Début de période')),
                ('periode_fin', models.DateField(help_text='Date de fin de la période de calcul', verbose_name='Fin de période')),
                ('total_absences', models.PositiveIntegerField(default=0, verbose_name='Total absences')),
                ('total_retards', models.PositiveIntegerField(default=0, verbose_name='Total retards')),
                ('total_departs_anticipes', models.PositiveIntegerField(default=0, verbose_name='Total départs anticipés')),
                ('absences_justifiees', models.PositiveIntegerField(default=0, verbose_name='Absences justifiées')),
                ('absences_non_justifiees', models.PositiveIntegerField(default=0, verbose_name='Absences non justifiées')),
                ('heures_cours_manquees', models.PositiveIntegerField(default=0, help_text="Nombre d'heures de cours manquées (absences seulement)", verbose_name='Heures de cours manquées')),
                ('calculee_le', models.DateTimeField(auto_now=True, verbose_name='Calculée le')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='academic.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': "Statistiques d'absences",
                'verbose_name_plural': "Statistiques d'absences",
                'constraints': [models.UniqueConstraint(fields=('eleve', 'periode_debut', 'periode_fin'), name='unique_stats_per_eleve_periode')],
            },
        ),
    ]
